#Reference: https://www.mkdocs.org/user-guide/configuration/

site_name: 'OpenDI: JSON Schema (DRAFT)'
repo_url: https://github.com/opendi-org/json-schema
edit_uri: blob/dev/docs     #URI Partial, added to repo URL to link to editable version of user's current page

docs_dir: "docs"            #Local directory for docs .md files

nav:
  - Schema: 'index.md'
  - 'Sample Data': 'test-data.md'
  - OpenDI:
    - Home: "https://opendi-org.github.io/landing-site"
    - Glossary: 'https://opendi-org.github.io/landing-site/OpenDI Glossary'
    - 'How to Contribute': 'https://opendi-org.github.io/landing-site/How To Contribute'

# Exclude _Role Page Template.md
exclude_docs: |
  _*.md

# theme:
#   name: mkdocs
#   color_mode: auto
#   user_color_mode_toggle: true
#   navigation_depth: 5


# Material is a third-party theme
# https://squidfunk.github.io/mkdocs-material/
theme:
  name: material

  favicon: img/opendi-icon-small.png
  logo: img/opendi-icon.png

  features:
    - toc.follow
  
  palette: 
    # Palette toggle for light mode
    - scheme: default